// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5r02CioZ8JgnFgCWObiDqH12V4Spbqn0',
    appId: '1:856797148723:android:d546b6ee379e6f1bfe9546',
    messagingSenderId: '856797148723',
    projectId: 'fidelin-b1ad0',
    databaseURL: 'https://fidelin-b1ad0-default-rtdb.firebaseio.com',
    storageBucket: 'fidelin-b1ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPnXEgc1pRx_zutx9Smu70JwZH3WCfuuI',
    appId: '1:856797148723:ios:e4b2d164eddcad72fe9546',
    messagingSenderId: '856797148723',
    projectId: 'fidelin-b1ad0',
    databaseURL: 'https://fidelin-b1ad0-default-rtdb.firebaseio.com',
    storageBucket: 'fidelin-b1ad0.appspot.com',
    iosClientId: '856797148723-2o7cltufi13u876rj0s5tp90bgngui8v.apps.googleusercontent.com',
    iosBundleId: 'com.fidelin.customer',
  );
}
